### ISSUE TITLE
WooCommerce - add iDEAL payment method

### ISSUE THREAD

**Issue by bp-rzahradka** [better-payment/bp-plugin-woocommerce-api2#5]
Please add iDEAL payment method to our `WooCommerce Plugin` using the payment processor `DB iDEAL` during tests.
Test Bank: `TESTNL2A`

**Comment by gadimbaylisahil** [comment]
@hasanzade-hasan 

Please, add "IDEAL" payment method(it's an async one with no config requirement) to WooCommerce.

Payment Type: "ideal"

Works the same way as PayPal and other async ones.
